### PR TITLE
Prevent leaking repEp.sender goroutines by closing repEp.q on nil RecvMsg()

### PR DESCRIPTION
**Pull request by ngConsulti**
First, I'm loving mangos. Absolutely first-rate!

Second, I may not be using it right. ;-)

But, when stress-testing a REP socket with 1000s of REQ, each creating and then closing a new TCP connection, I noticed that the process seemed to be leaking goroutines, eventually resulting in an out-of-memory failure.

This PR attempts to prevent the leak in the simplest way possible.

### CODE REVIEW

**Comment by gdamore** [comment]
So as you can see the CI tests failed.  That said, I'm also keen to understand the failure you've seen that prompted you to try to make this change.  I think you should not see any "goroutines" leak -- we cleanly return from the receiver() go routine.

How are you closing the TCP connection, btw?  You should not close directly any TCP connection associated with mangos (mangos should "own" the underlying socket), but you *can* close the endpoint using mangos Close() function.

That said, I can see a situation where the underlying net.Conn leaks if you arrange somehow to close the underlying file descriptor.  At that point, we'll get an error from the transport implementation, which we never expect to happen.  We expect Recv() to always block waiting a message unless the net.Conn has encountered a fatal error.

That said, I can see where in the Recv() handling we could forcibly Close() that net.Conn on error.

Closing the pe.q is almost certainly a mistake.  This should only ever be closed if the upper sender() has terminated -- otherwise you can wind up with a situation where the upper sender winds up panic'ing trying to write to a closed channel.

**Comment by gdamore** [comment]
Yeah, I think its quite possible that we are leaking the net.Conn, and leaving the endpoint still stuck.  Its not immediately clear to me how tragic this is.

I think the right answer here is to fix the transports so that when the encounter the error, they go ahead and shutdown any underlying connection.  For example, in conn.go, the Recv() routine should do p.c.Close() for any of those error conditions -- I think we can reasonably safely assume *any* error condition is fatal to the TCP connection.

**Comment by gdamore** [comment]
Oh wait... I stand corrected.  the pipe() code takes care of this automatically - the underlying connection is closed when the transport errors out.  In fact, there is an incorrect double close in one of the cases -- the case where the message sent is too large (that's a bug!)

So I'm now really confused about your leak.  Can you provide a test program?

**Comment by gdamore** [comment]
Ok, I found this bug, and I've got another version of the fix, it affects quite a bit of things.  And I see your leaking go routines.

**Comment by gdamore** [comment]
See the fix for #136 which I think fixes this.

**Comment by ngConsulti** [comment]
Yes. Looks like #136 is the general fix. Thanks and closing!

**Pull request closed without merging**
