### PR TITLE
Perf enhancement

### PR DESCRIPTION
**Pull request by dzyp**
Was running through some code and saw this pretty simple change to pull some somewhat expensive string operations outside of the lock.

### CODE REVIEW

**Comment by gdamore** [comment]
Looks pretty good.   Note that the code in question is not on any hot paths normally but it's still a good improvement.

**Comment by gdamore** [comment]
Can you please rebase this down to a single commit and use the comment syntax of "fixes #<bug> <synopsis>"?  I'm trying to apply a fairly tight policy about keeping the git history clean. (If not I can do it for you but then you'll have to merge on your end later.)

Thanks.

**Comment by gdamore** [comment]
Stupid syntax markdown ate my comment syntax.  Just check the history for the last few commits for the syntax.  It's bug id and synopsis.

**Comment by tylertreat** [comment]
As an aside, I've found `defer` to add quite a bit of overhead. Really only an issue on critical paths (as Garrett mentioned, this particular one isn't), but I try to avoid them if there aren't too many return points.

**Comment by gdamore** [comment]
That's interesting and good to know.  And somewhat surprising. One would have believed that defer could have been resolved statically by the compiler. I guess future optimization work for the go compiler.

**Comment by tylertreat** [comment]
Yep, it's something they say will improve, but there's definitely overhead with it currently.

**Comment by dustinhiatt-wf** [comment]
@gdamore, the defer function actually executes when it's called (ie, all function parameters are evaluated at the defer call) so it's probably not something that the compiler can just does some escape analysis on (which they already do to determine if a value goes on the stack or heap).  

The performance overhead is likely from the fact that to support this behavior they have to copy state at the defer call.

**Comment by gdamore** [comment]
I did the rebase and commit history fixup, and merged:

fixed in 15c09239eba4fe0d5d910034271cec63fed8a1ef

**Comment by gdamore** [comment]
Experimentally, I'm not seeing any noticeable difference with defer vs. explicit unlock.  I'll post more shortly.

**Comment by dustinhiatt-wf** [comment]
@gdamore, I think you can really only notice this overhead in really really tight loops.  Here is an example: https://github.com/Workiva/go-datastructures/pull/60

**Comment by gdamore** [comment]
So, I just benchmarked it myself.  The difference is about 80 nsec (on my MacOS X 10.10 system with golang 1.4.1 on an i7).  Too small to notice in most cases, as this is smaller than the latency noise in other things, but I'm going to submit a PR shortly to switch to this in the hot path.

**Pull request closed without merging**
